//! The immutable template an `Agent` hands to the loop. Shared behind an `Arc` so cloning an agent does not duplicate its tool registry or sub-agent tree.

use std::collections::HashMap;
use std::time::Duration;

use serde_json::Value;

use crate::provider::model::Model;
use crate::tools::ToolRegistry;

use crate::output::OutputSchema;

use super::agent::Agent;
use super::prompts;

/// The agent's definition. Shared across clones via `Arc<AgentSpec>` with copy-on-write
/// on builder mutations, then passed to `run_loop` directly.
///
/// `name` is eagerly generated by `Agent::new()` and overwritten by `.name(...)`.
/// `model: None` at template level means "inherit from parent"; after `Agent::compile`
/// it is always `Some` (use `AgentSpec::model()` to unwrap).
#[derive(Clone)]
pub(crate) struct AgentSpec {
    pub name: String,
    pub model: Option<Model>,
    pub role: String,
    pub behavior: String,
    pub context: Option<String>,
    pub tool_registry: ToolRegistry,
    pub hires: Vec<Agent>,
    pub contract: Option<OutputSchema>,
    pub max_request_tokens: Option<u32>,
    pub max_input_tokens: Option<u64>,
    pub max_output_tokens: Option<u64>,
    pub max_turns: Option<u32>,
    pub max_contract_retries: Option<u32>,
    pub max_request_retries: u32,
    pub request_retry_delay: Duration,
    pub keep_alive: bool,
}

impl Default for AgentSpec {
    fn default() -> Self {
        Self {
            name: crate::util::generate_agent_name("agent"),
            model: None,
            role: String::new(),
            behavior: prompts::DEFAULT_BEHAVIOR.to_string(),
            context: None,
            tool_registry: ToolRegistry::new(),
            hires: Vec::new(),
            contract: None,
            max_request_tokens: None,
            max_input_tokens: None,
            max_output_tokens: None,
            max_turns: None,
            max_contract_retries: Some(10),
            max_request_retries: AgentSpec::DEFAULT_MAX_REQUEST_RETRIES,
            request_retry_delay: AgentSpec::DEFAULT_REQUEST_RETRY_DELAY,
            keep_alive: false,
        }
    }
}

impl AgentSpec {
    /// Default number of retries for transient API errors. Re-exported as
    /// `Agent::DEFAULT_MAX_REQUEST_RETRIES` for the public API surface.
    pub const DEFAULT_MAX_REQUEST_RETRIES: u32 = 10;

    /// Default base delay for the exponential-backoff retry policy.
    /// Re-exported as `Agent::DEFAULT_REQUEST_RETRY_DELAY`.
    pub const DEFAULT_REQUEST_RETRY_DELAY: Duration = Duration::from_millis(500);

    /// Read the resolved model. Panics if called on an unresolved spec — only
    /// `Agent::compile` is supposed to observe a spec whose model is `None`.
    pub(crate) fn model(&self) -> &Model {
        self.model
            .as_ref()
            .expect("AgentSpec::model() called on unresolved spec; Agent::compile must run first")
    }

    /// Build the provider's `system` field from `role` (with `vars`
    /// interpolated), `behavior`, and a JSON-output directive when
    /// `contract` is set.
    pub(crate) fn system_prompt(&self, vars: &HashMap<String, Value>) -> String {
        let mut s = Self::interpolate(&self.role, vars);
        if !self.behavior.is_empty() {
            s.push_str("\n\n");
            s.push_str(&self.behavior);
        }
        if self.contract.is_some() {
            s.push_str(prompts::STRUCTURED_OUTPUT_INSTRUCTION);
        }
        s
    }

    /// Resolve the first user message's context payload. `None` at the field
    /// means "use the runtime default"; `Some("")` is an explicit opt-out
    /// (returns `None` here so the loop skips the message); `Some(s)` is a
    /// full override sent verbatim.
    pub(crate) fn context(&self, default: &str) -> Option<String> {
        match self.context.as_deref() {
            None => Some(default.to_string()),
            Some("") => None,
            Some(s) => Some(s.to_string()),
        }
    }

    /// Replace `{key}` placeholders in `template` with stringified values.
    pub(crate) fn interpolate(template: &str, vars: &HashMap<String, Value>) -> String {
        let mut result = template.to_string();
        for (key, value) in vars {
            let replacement = match value {
                Value::String(s) => s.clone(),
                other => other.to_string(),
            };
            result = result.replace(&format!("{{{key}}}"), &replacement);
        }
        result
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const DEFAULT: &str = "<environment>\ndefault\n</environment>";

    #[test]
    fn unset_context_uses_runtime_default() {
        let spec = AgentSpec::default();
        assert_eq!(spec.context(DEFAULT), Some(DEFAULT.to_string()));
    }

    #[test]
    fn custom_context_replaces_default() {
        let mut spec = AgentSpec::default();
        spec.context = Some("only this".to_string());
        assert_eq!(spec.context(DEFAULT), Some("only this".to_string()));
    }

    #[test]
    fn empty_context_opts_out() {
        let mut spec = AgentSpec::default();
        spec.context = Some(String::new());
        assert_eq!(spec.context(DEFAULT), None);
    }
}
