"""Type stubs for the agentwerk Python bindings."""

from typing import Any, Awaitable, Callable, Optional, overload

class Provider:
    """An LLM provider, passed to ``Agent.provider(...)``."""

    @staticmethod
    def from_env() -> "Provider": ...
    async def verify(self, model: str) -> None: ...

class Model:
    """A model name, with an optional context window size and reasoning level."""

    def __init__(self, name: str) -> None: ...
    @staticmethod
    def from_env() -> "Model": ...
    def context_window(self, size: int) -> "Model": ...
    def reasoning_effort(self, effort: str) -> "Model": ...
    def get_name(self) -> str: ...
    def get_context_window(self) -> Optional[int]: ...
    def get_reasoning_effort(self) -> str: ...

def Anthropic(
    api_key: str, base_url: Optional[str] = ..., timeout: Optional[float] = ...
) -> Provider: ...
def OpenAi(
    api_key: str, base_url: Optional[str] = ..., timeout: Optional[float] = ...
) -> Provider: ...
def Mistral(
    api_key: str, base_url: Optional[str] = ..., timeout: Optional[float] = ...
) -> Provider: ...
def LiteLlm(
    api_key: str, base_url: Optional[str] = ..., timeout: Optional[float] = ...
) -> Provider: ...

class Tool:
    """A tool an agent may call, passed to ``Agent.tool(...)``."""

    def timeout(self, seconds: float) -> "Tool": ...

def ReadFileTool() -> Tool: ...
def WriteFileTool() -> Tool: ...
def EditFileTool() -> Tool: ...
def GrepTool() -> Tool:
    """Search file contents by regular expression, or by code shape with ``syntax="code"``."""
    ...
def GlobTool() -> Tool: ...
def ListDirectoryTool() -> Tool: ...
def KnowledgeTool(store: "Knowledge") -> Tool: ...
def TaskTool() -> Tool: ...
def EventTool() -> Tool: ...
def FinishTool() -> Tool: ...

class FetchTool:
    """Fetch a URL and read its body, passed to ``Agent.tool(...)``."""

    def __init__(self) -> None: ...
    def impersonate(self) -> "FetchTool":
        """Send browser headers and HTTP/2 settings without changing the TLS ClientHello."""
        ...
    def timeout(self, seconds: float) -> "FetchTool": ...

class CommandTool:
    """A command an agent may call, passed to ``Agent.tool(...)``."""

    def __init__(self, name: str) -> None: ...
    def allow(self, pattern: str) -> "CommandTool": ...
    def allow_flag(self, flag: str) -> "CommandTool": ...
    def deny(self, pattern: str) -> "CommandTool": ...
    def deny_flag(self, flag: str) -> "CommandTool": ...
    def description(self, description: str) -> "CommandTool": ...
    def concurrent(self, concurrent: bool) -> "CommandTool": ...
    def timeout(self, seconds: float) -> "CommandTool": ...

@overload
def tool(func: Callable[..., Any]) -> Callable[..., Any]: ...
@overload
def tool(
    *,
    concurrent: bool = ...,
    schema: Optional[dict] = ...,
    name: Optional[str] = ...,
    description: Optional[str] = ...,
    timeout: float = ...,
) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...

class Schema:
    def __init__(self, document: dict[str, Any]) -> None: ...
    def validate(self, value: Any) -> tuple[Any, list[str]]: ...

class ReplyContent:
    """One block inside a reply: text, a tool call, a tool result, or reasoning."""

    @staticmethod
    def text(text: str) -> "ReplyContent": ...
    @staticmethod
    def tool_use(id: str, name: str, input: Any) -> "ReplyContent": ...
    @staticmethod
    def tool_result(
        tool_use_id: str,
        content: str,
        succeeded: bool = ...,
        path: Optional[str] = ...,
    ) -> "ReplyContent": ...
    @staticmethod
    def thinking(thinking: str, signature: str) -> "ReplyContent": ...
    @staticmethod
    def redacted_thinking(data: str) -> "ReplyContent": ...
    def get_kind(self) -> str: ...
    def get_data(self) -> dict: ...
    def __repr__(self) -> str: ...

class Reply:
    """One entry in a task's replies."""

    @staticmethod
    def user_text(text: str) -> "Reply": ...
    def get_author(self) -> str: ...
    def get_content(self) -> list[ReplyContent]: ...
    def get_created_at(self) -> int: ...
    def __repr__(self) -> str: ...

class Query:
    """Select tasks, events, or joined task-event rows with AQL.

    A lone value is task-label shorthand, except that ``t-N`` selects a task
    ID. Fields in full expressions are qualified with ``task.`` or ``event.``.
    Using both evaluates task-event pairs linked through ``event.task_id``. The
    receiving operation projects matches to its return type. Queries may
    include ``ORDER BY <field> ASC | DESC``.
    """

    def __init__(self, query: str) -> None: ...
    def __repr__(self) -> str: ...

class Condition:
    """Release agents and tasks once per run when an AQL query matches."""

    def __init__(self, aql: str) -> None: ...
    def id(self, id: str) -> "Condition": ...
    def add_agent(self, agent: "Agent") -> "Condition": ...
    def add_task(self, task: "Task | Any") -> "Condition": ...

class Task:
    def __init__(
        self,
        task: Any,
        *,
        label: Optional[str] = ...,
        schema: Optional[Schema] = ...,
    ) -> None: ...
    def get_id(self) -> str: ...
    def get_status(self) -> str: ...
    def get_task(self) -> Any: ...
    def get_result(self) -> Optional[Any]: ...
    def get_label(self) -> Optional[str]: ...
    def get_schema(self) -> Optional[Schema]: ...
    def get_reporter(self) -> str: ...
    def get_assignee(self) -> Optional[str]: ...
    def get_created_at(self) -> int: ...
    def get_started_at(self) -> Optional[int]: ...
    def get_finished_at(self) -> Optional[int]: ...
    def get_failed_at(self) -> Optional[int]: ...
    def get_replies(self) -> list[Reply]: ...
    def get_errors(self) -> list[Event]: ...
    def is_todo(self) -> bool: ...
    def is_finished(self) -> bool: ...
    def is_failed(self) -> bool: ...
    def is_in_progress(self) -> bool: ...
    def is_pending(self) -> bool: ...
    def is_cancelled(self) -> bool: ...
    def __repr__(self) -> str: ...

class Trajectory:
    @staticmethod
    def from_task(
        agent_id: str, model: Optional[str], task: Task
    ) -> "Trajectory": ...
    def save(self, dir: str) -> None: ...
    def get_id(self) -> str: ...
    def get_model(self) -> Optional[str]: ...
    def get_replies(self) -> list[Reply]: ...
    def __repr__(self) -> str: ...

class Page:
    def __init__(
        self,
        slug: str,
        description: str,
        content: str,
        kind: str = ...,
        tags: Optional[list[str]] = ...,
    ) -> None: ...
    def get_slug(self) -> str: ...
    def get_kind(self) -> str: ...
    def get_description(self) -> str: ...
    def get_content(self) -> str: ...
    def get_tags(self) -> list[str]: ...
    def __repr__(self) -> str: ...

class Pages:
    def save(self, page: Page) -> None: ...
    def get_page(self, slug: str) -> Page: ...
    def get_all(self) -> list[Page]: ...
    def remove(self, slug: str) -> None: ...

class Knowledge:
    @staticmethod
    def load(knowledge_dir: str) -> "Knowledge": ...
    def set_index_char_limit(self, count: int) -> "Knowledge": ...
    def get_index_char_limit(self) -> int: ...
    def get_index(self) -> str: ...
    def get_pages(self) -> Pages: ...
    def clear(self) -> None: ...

class Event:
    RUN_STARTED: str
    RUN_FINISHED: str
    TASK_CREATED: str
    TASK_STARTED: str
    TASK_FINISHED: str
    TASK_FAILED: str
    TURN_STARTED: str
    REQUEST_STARTED: str
    REQUEST_FINISHED: str
    PROMPT_RENDER_FAILED: str
    REQUEST_FAILED: str
    REQUEST_RETRIED: str
    TEXT_CHUNK_RECEIVED: str
    TOOL_CALL_REPAIRED: str
    TOOL_CALL_DECLINED: str
    TOOL_CALL_STARTED: str
    TOOL_CALL_FINISHED: str
    TOOL_CALL_FAILED: str
    KNOWLEDGE_WRITTEN: str
    KNOWLEDGE_READ: str
    KNOWLEDGE_REMOVED: str
    KNOWLEDGE_LISTED: str
    KNOWLEDGE_FAILED: str
    POLICY_VIOLATED: str
    SCHEMA_RETRIED: str
    COMPACTION_STARTED: str
    COMPACTION_PROGRESS: str
    COMPACTION_FINISHED: str
    COMPACTION_FAILED: str
    def __init__(self, name: str) -> None: ...
    @staticmethod
    def run_started() -> "Event": ...
    @staticmethod
    def run_finished(outcome: Any) -> "Event": ...
    @staticmethod
    def task_created() -> "Event": ...
    @staticmethod
    def task_started() -> "Event": ...
    @staticmethod
    def task_finished() -> "Event": ...
    @staticmethod
    def task_failed() -> "Event": ...
    @staticmethod
    def turn_started() -> "Event": ...
    @staticmethod
    def request_started(model: str) -> "Event": ...
    @staticmethod
    def request_finished(model: str, usage: Any) -> "Event": ...
    @staticmethod
    def prompt_render_failed(expression: str, message: str) -> "Event": ...
    @staticmethod
    def request_failed(model: str, kind: str, message: str) -> "Event": ...
    @staticmethod
    def request_retried(
        model: str, attempt: int, max_attempts: int, kind: str, message: str
    ) -> "Event": ...
    @staticmethod
    def text_chunk_received(content: str) -> "Event": ...
    @staticmethod
    def tool_call_repaired(
        tool_name: str, call_id: str, kind: str, message: str
    ) -> "Event": ...
    @staticmethod
    def tool_call_declined(tool_name: str, kind: str) -> "Event": ...
    @staticmethod
    def tool_call_started(tool_name: str, call_id: str, input: Any) -> "Event": ...
    @staticmethod
    def tool_call_finished(output: str) -> "Event": ...
    @staticmethod
    def tool_call_failed(message: str) -> "Event": ...
    @staticmethod
    def knowledge_written(slug: str) -> "Event": ...
    @staticmethod
    def knowledge_read(slug: str) -> "Event": ...
    @staticmethod
    def knowledge_removed(slug: str) -> "Event": ...
    @staticmethod
    def knowledge_listed() -> "Event": ...
    @staticmethod
    def knowledge_failed(action: str, slug: str, kind: str, message: str) -> "Event": ...
    @staticmethod
    def policy_violated(policy: str, limit: int) -> "Event": ...
    @staticmethod
    def schema_retried(
        attempt: int, max_attempts: int, kind: str, message: str
    ) -> "Event": ...
    @staticmethod
    def compaction_started(trigger: str, total: int) -> "Event": ...
    @staticmethod
    def compaction_progress(trigger: str, completed: int, total: int) -> "Event": ...
    @staticmethod
    def compaction_finished(trigger: str) -> "Event": ...
    @staticmethod
    def compaction_failed(trigger: str, kind: str, message: str) -> "Event": ...
    def data(self, data: Any) -> "Event": ...
    def directive(self, directive: str) -> "Event": ...
    def task_id(self, task_id: str) -> "Event": ...
    def agent_id(self, agent_id: str) -> "Event": ...
    def get_name(self) -> str: ...
    def get_directive(self) -> Optional[str]: ...
    def get_data(self) -> Any: ...
    def get_task_id(self) -> str: ...
    def get_agent_id(self) -> str: ...
    def get_label(self) -> Optional[str]: ...
    def get_created_at(self) -> int: ...
    def __repr__(self) -> str: ...

class Agent:
    """An LLM agent that uses the tools you provide to complete tasks."""

    def __init__(self) -> None: ...
    @staticmethod
    def from_env() -> "Agent": ...
    def provider(self, provider: Provider) -> "Agent": ...
    def model(self, model: "str | Model") -> "Agent": ...
    def role(self, role: str) -> "Agent": ...
    def label(self, label: str) -> "Agent": ...
    def interactive(self) -> "Agent": ...
    def template(self, key: str, value: str) -> "Agent": ...
    def templates(self, variables: "dict[str, str]") -> "Agent": ...
    def dir(self, dir: str) -> "Agent": ...
    def knowledge(self, store: Knowledge) -> "Agent": ...
    def directive(self, key: str, template: str) -> "Agent": ...
    def directives(self, overrides: dict[str, str]) -> "Agent": ...
    def tool(self, tool: Any) -> "Agent": ...
    def tools(self, tools: list) -> "Agent": ...
    def get_id(self) -> str: ...
    def add_task(self, task: "Task | Any") -> str: ...
    def start(self) -> "Werk": ...
    async def finish_task(
        self, matches: "Query | str | Callable[[Task], bool]"
    ) -> Optional[Any]: ...
    async def finish_tasks(
        self, matches: "Query | str | Callable[[Task], bool]"
    ) -> list[Any]: ...
    async def finish(self) -> list[Any]: ...

class Policy:
    max_turns: Optional[int]
    max_input_tokens: Optional[int]
    max_output_tokens: Optional[int]
    max_request_tokens: Optional[int]
    max_schema_retries: Optional[int]
    max_request_retries: int
    request_retry_delay: float
    max_time: Optional[float]
    compaction_threshold: Optional[float]

    def __init__(
        self,
        *,
        max_turns: Optional[int] = ...,
        max_input_tokens: Optional[int] = ...,
        max_output_tokens: Optional[int] = ...,
        max_request_tokens: Optional[int] = ...,
        max_schema_retries: Optional[int] = ...,
        max_request_retries: Optional[int] = ...,
        request_retry_delay: Optional[float] = ...,
        max_time: Optional[float] = ...,
        compaction_threshold: Optional[float] = ...,
    ) -> None: ...

class Werk:
    def __init__(self) -> None: ...
    @staticmethod
    def load(werk_dir: str) -> "Werk": ...
    def set_template(self, key: str, value: str) -> "Werk": ...
    def set_templates(self, variables: "dict[str, str]") -> "Werk": ...
    def set_policy(self, policy: "Policy") -> "Werk": ...
    def get_policy(self) -> "Policy": ...
    def set_dir(self, dir: str) -> "Werk": ...
    def get_dir(self) -> str: ...
    def add_agent(self, agent: Agent) -> "Werk": ...
    def add_condition(self, condition: Condition) -> str: ...
    def add_task(self, task: "Task | Any") -> str: ...
    def add_reply(self, id: str, content: str) -> "Werk": ...
    def emit_event(self, event: Event) -> Event: ...
    def edit_replies(
        self, id: str, editor: Callable[[list[Reply]], Optional[list[Reply]]]
    ) -> "Werk": ...
    def set_task_finished(self, id: str, result: Any) -> None: ...
    def set_task_failed(self, id: str) -> None: ...
    def on_event(
        self, handler: Callable[["Werk", Event], Any]
    ) -> "Werk": ...
    def on_event_async(
        self, handler: Callable[["Werk", Event], Awaitable[Any]]
    ) -> "Werk": ...
    def on_result(
        self, handler: Callable[["Werk", Task, Any], Any]
    ) -> "Werk": ...
    def on_result_async(
        self, handler: Callable[["Werk", Task, Any], Awaitable[Any]]
    ) -> "Werk": ...
    def on_failure(
        self, handler: Callable[["Werk", Event, Task], Any]
    ) -> "Werk": ...
    def on_failure_async(
        self, handler: Callable[["Werk", Event, Task], Awaitable[Any]]
    ) -> "Werk": ...
    def on_task(
        self, handler: Callable[["Werk", Event, Task], Any]
    ) -> "Werk": ...
    def on_task_async(
        self, handler: Callable[["Werk", Event, Task], Awaitable[Any]]
    ) -> "Werk": ...
    def start(self) -> "Werk": ...
    async def finish_task(
        self, matches: "Query | str | Callable[[Task], bool]"
    ) -> Optional[Any]: ...
    async def finish_tasks(
        self, matches: "Query | str | Callable[[Task], bool]"
    ) -> list[Any]: ...
    async def finish(self) -> list[Any]: ...
    def cancel_tasks(
        self, matches: "Query | str | Callable[[Task], bool]"
    ) -> "Werk": ...
    def cancel(self) -> "Werk": ...
    def get_task(self, id: str) -> Optional[Task]: ...
    def get_tasks(self) -> list[Task]: ...
    def find_task(
        self, predicate: "Query | str | Callable[[Task], bool]"
    ) -> Optional[Task]: ...
    def find_tasks(
        self, predicate: "Query | str | Callable[[Task], bool]"
    ) -> list[Task]: ...
    def get_results(self) -> list[Any]: ...
    def find_result(
        self, query: "Query | str | Callable[[Task], bool]"
    ) -> Optional[Any]: ...
    def find_results(
        self, query: "Query | str | Callable[[Task], bool]"
    ) -> list[Any]: ...
    def find_event(
        self, matches: "Query | str | Callable[[Event], bool]"
    ) -> Optional[Event]: ...
    def find_events(
        self, matches: "Query | str | Callable[[Event], bool]"
    ) -> list[Event]: ...
    def get_finish_reason(self) -> Optional[str]: ...
    def get_model_for_agent(self, agent_id: str) -> Optional[str]: ...
    def get_input_tokens(self) -> int: ...
    def get_output_tokens(self) -> int: ...
    def get_duration(self) -> Optional[float]: ...
